import type { LevelModifierDefinition } from "../src/interfaces.ts";

/** Transparent 60/40 wheel odds; positive weights sum to 6 and negatives to 4. */
export const modifierWheelConfig = {
  spinDurationMs: 4100,
  rotations: 6,
  positiveWeight: 1.5,
  negativeWeight: 1,
  ticksPerRevolution: 8,
  confettiPieces: 24,
} as const;

export const levelModifiers: readonly LevelModifierDefinition[] = [
  {
    id: "speedBoost",
    kind: "positive",
    weight: modifierWheelConfig.positiveWeight,
    icon: "⚡",
    name: "TURBO SPONGE",
    shortName: "Turbo",
    effectText: "+25% movement speed",
    effects: { playerSpeed: 1.25 },
  },
  {
    id: "miniSponge",
    kind: "negative",
    weight: modifierWheelConfig.negativeWeight,
    icon: "🔻",
    name: "MINI SPONGE",
    shortName: "Mini",
    effectText: "SpongeBob shrinks to 80% size · 20% less water capacity",
    effects: { playerScale: 0.8, waterCapacity: 0.8 },
  },
  {
    id: "waterBoost",
    kind: "positive",
    weight: modifierWheelConfig.positiveWeight,
    icon: "💧",
    name: "SUPER SOAKER",
    shortName: "Soaker",
    effectText: "+35% water absorption · +25% capacity",
    effects: { absorptionSpeed: 1.35, waterCapacity: 1.25 },
  },
  {
    id: "reducedWater",
    kind: "negative",
    weight: modifierWheelConfig.negativeWeight,
    icon: "💧⬇",
    name: "DRY SPONGE",
    shortName: "Dry",
    effectText: "−25% absorption speed · −20% capacity",
    effects: { absorptionSpeed: 0.75, waterCapacity: 0.8 },
  },
  {
    id: "slowBeton",
    kind: "positive",
    weight: modifierWheelConfig.positiveWeight,
    icon: "🐌",
    name: "BETON BRAKE",
    shortName: "Brake",
    effectText: "Dr. Beton moves and acts 25% slower",
    effects: { betonSpeed: 0.75 },
  },
  {
    id: "angryBeton",
    kind: "negative",
    weight: modifierWheelConfig.negativeWeight,
    icon: "😡",
    name: "ANGRY DR. BETON",
    shortName: "Angry",
    effectText: "+20% speed · fiercer eyes and cracks",
    effects: { betonSpeed: 1.2, angryBeton: true },
  },
  {
    id: "doubleCoins",
    kind: "positive",
    weight: modifierWheelConfig.positiveWeight,
    icon: "🪙",
    name: "DOUBLE COINS",
    shortName: "Coins",
    effectText: "Double coin rewards",
    effects: { coinReward: 2 },
  },
  {
    id: "heatWave",
    kind: "negative",
    weight: modifierWheelConfig.negativeWeight,
    icon: "🌡️",
    name: "HEAT WAVE",
    shortName: "Heat wave",
    effectText: "+12% warming this level",
    effects: { heatWarming: 1.12 },
  },
];
