import type { LevelModifierDefinition } from "../src/interfaces";

/** Transparent 60/40 wheel odds; positive weights sum to 6 and negatives to 4. */
export const modifierWheelConfig = {
  spinDurationMs: 4100,
  rotations: 6,
  positiveWeight: 1.5,
  negativeWeight: 1,
  ticksPerRevolution: 8,
  confettiPieces: 24,
} as const;

export const levelModifiers: readonly LevelModifierDefinition[] = [
  {
    id: "speedBoost",
    kind: "positive",
    weight: modifierWheelConfig.positiveWeight,
    icon: "⚡",
    name: "TURBO-SCHWAMM",
    shortName: "Turbo",
    effectText: "+25% Bewegungsgeschwindigkeit",
    effects: { playerSpeed: 1.25 },
  },
  {
    id: "miniSponge",
    kind: "negative",
    weight: modifierWheelConfig.negativeWeight,
    icon: "🔻",
    name: "MINI-SCHWAMM",
    shortName: "Mini",
    effectText: "SpongeBob schrumpft auf 80% Größe",
    effects: { playerScale: 0.8 },
  },
  {
    id: "waterBoost",
    kind: "positive",
    weight: modifierWheelConfig.positiveWeight,
    icon: "💧",
    name: "SUPER-SAUGER",
    shortName: "Sauger",
    effectText: "+35% Wasseraufnahme · +25% Kapazität",
    effects: { absorptionSpeed: 1.35, waterCapacity: 1.25 },
  },
  {
    id: "reducedWater",
    kind: "negative",
    weight: modifierWheelConfig.negativeWeight,
    icon: "💧⬇",
    name: "TROCKENER SCHWAMM",
    shortName: "Trocken",
    effectText: "−25% Saugtempo · −20% Kapazität",
    effects: { absorptionSpeed: 0.75, waterCapacity: 0.8 },
  },
  {
    id: "slowBeton",
    kind: "positive",
    weight: modifierWheelConfig.positiveWeight,
    icon: "🐌",
    name: "BETON-BREMSE",
    shortName: "Bremse",
    effectText: "Dr. Beton bewegt und handelt 25% langsamer",
    effects: { betonSpeed: 0.75 },
  },
  {
    id: "angryBeton",
    kind: "negative",
    weight: modifierWheelConfig.negativeWeight,
    icon: "😡",
    name: "DR. BETON WIRD WÜTEND",
    shortName: "Wütend",
    effectText: "+20% Tempo · stärkere Augen und Risse",
    effects: { betonSpeed: 1.2, angryBeton: true },
  },
  {
    id: "doubleCoins",
    kind: "positive",
    weight: modifierWheelConfig.positiveWeight,
    icon: "🪙",
    name: "DOPPEL-MÜNZEN",
    shortName: "Münzen",
    effectText: "Doppelte Münzbelohnungen",
    effects: { coinReward: 2 },
  },
  {
    id: "heatWave",
    kind: "negative",
    weight: modifierWheelConfig.negativeWeight,
    icon: "🌡️",
    name: "HITZEWELLE",
    shortName: "Hitzewelle",
    effectText: "+12% Wärmeaufbau in diesem Level",
    effects: { heatWarming: 1.12 },
  },
];
