/** Original ambient character; no rewards, quests or gameplay powers. */
export const riversideBuddy = {
  x: 8.5,
  z: -1.5,
  radiusX: 2.4,
  radiusZ: 2.1,
  speed: 0.18,
  cycleSeconds: 78,
  messageSeconds: 9,
  voicePitch: 155,
  collisionRadius: 0.42,
  messages: [
    "Small steps. Big difference!",
    "Less concrete, more life!",
    "Every open patch helps.",
    "You're doing good. Keep going!",
    "More roots, cooler streets!",
    "Give the rain somewhere to stay.",
    "Cheers to a greener Basel!",
    "You've got this, neighbour!",
    "A little shade goes a long way.",
    "Good things take a little care.",
    "Make room for tomorrow.",
    "Look at you making a difference!",
    "Every drop deserves a home.",
    "Take a breath. You're doing fine.",
    "Grow something good today.",
    "Nice work! Keep the good flowing.",
    "The city feels better with you.",
    "One patch at a time, friend.",
    "Leave it a little better.",
    "Good vibes. Good roots.",
  ],
} as const;
