// Generated by the in-game level builder (vite.config.ts); do not edit by hand.
import type { BuiltLevel } from "../../src/interfaces";

/** Levels saved from the builder, keyed by level id. */
export const builtLevels: Record<string, BuiltLevel> = {};
